### ISSUE TITLE
Compile errors with Haxe 3.3.0 development builds

### ISSUE THREAD

**Issue by jgranick** [misprintt/mockatoo#50]
Hi guys,

I have an issue that occurs only on the JavaScript target with Haxe 3.3 development builds (I believe it works with Haxe 3.2, but am unable to test in the environment that's using mockatoo right now)

https://github.com/HaxeFoundation/haxe/issues/4793#issuecomment-172259155

If there is anything about this that sounds like "Yes, mockatoo could be the cause" or "hey, I think I have an idea where in the code that might be happening", it would be a huge help! Thanks :smile:

**Comment by Simn** [comment]
See https://github.com/misprintt/mockatoo/blob/master/src/mockatoo/macro/ClassFields.hx#L321
See #9

**Comment by jgranick** [comment]
Ah, interesting! That might explain this works in C++, but not in JavaScript:

```haxe
if (arg.opt && Tools.isStaticPlatform())
{
	//NOTE(Dom) - this is to prevent #9 - optional method args without a `?` cause compilation error
	arg.opt = verifyOptionalArgIsActuallyNullable(arg);
}
```

**Comment by jgranick** [comment]
Fixed in https://github.com/misprintt/mockatoo/pull/51
